# Generated by Django 4.1.2 on 2022-11-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Unidad de medida')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad Medida',
                'verbose_name_plural': 'Unidad Medidas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado interno del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria', verbose_name='Categoria del producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.unidad_medida', verbose_name='Unidad de medida del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
