# Generated by Django 4.1.2 on 2022-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='Rut proveedor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Proveedor')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Proveedor')),
                ('detalle', models.TextField(max_length=255, verbose_name='Detalles productos proveeidos por el proveedor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado interno del proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
