# Generated by Django 4.1.2 on 2022-11-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventario',
            name='salidas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='salidas',
        ),
    ]
